### ISSUE TITLE
Initialize with links to a dummy node?

### ISSUE THREAD

**Issue by qzshadow** [bkj/pytorch-graphsage#3]
Hi,

I notice that when you create the adjacency matrix, you use the trick "Initialize w/ links to a dummy node" (see utils/convert.py  function make_adjacency), however, even if I change it to a normal adjacency matrix, the code still works, could you explain why to use this trick?

Thanks!

**Comment by bkj** [comment]
I don't remember precisely at the moment -- haven't looked at this code for a little while.  But I think it's just to handle zero-degree nodes.

If you look at the logic below, any node w/ nonzero degree in the training set would have `adj[node, :]` overwritten with non-dummy entries.

**Comment by qzshadow** [comment]
Thanks, I believe that you are right.
